#!/bin/bash

curl --silent --output schema.org.jsonld https://schema.org/version/latest/schemaorg-current-http.jsonld
curl --silent --output crate-context.jsonld https://www.researchobject.org/ro-crate/1.1/context.jsonld
node write-types.js
rm schema.org.jsonld
rm crate-context.jsonld